### ISSUE TITLE
Created date is coming out strange

### ISSUE THREAD

**Issue by RCatersels** [tieniber/PDF-Exporter#1]
Hello Eric,

Awsome app. Looking forward for an appstore release. I did found a small issue. See the attached document and look at the first field creation date. There goes something wrong in the date conversion language / country settings. The date comes out as 2015-58-04.

Regards,

Ronald

[RandomFileName1472110794648.pdf](https://github.com/tieniber/PDF-Exporter/files/436411/RandomFileName1472110794648.pdf)

**Comment by tieniber** [comment]
Could it be the different between capital and lowercase D and d for days? There is some way to print the "day of the year", I wonder if something like this is happening. Will play with it

**Comment by RCatersels** [comment]
See here: http://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html 

Regards.,

Ronald

**Comment by tieniber** [comment]
ok, looks like we were using "mm" instead of "MM" for Month in the default date format. That made it output minutes instead of month number, hence the 58 in your example.

I'll update the default, you can of course define your own custom format as well.

**Comment by tieniber** [comment]
Committed change and re-deploying sandbox as well.
